import Image from "next/image";
import Link from "next/link";
import { SectionLabel, TextLink } from "./editorial";
import { pathFor,text,type Locale } from "@/lib/site";
import type { ReactNode } from "react";
type HeroImage={image:string;imageAlt:string};
export function InstitutionHero({title,image,imageAlt}:{title:ReactNode}&HeroImage){return <section className="institution-hero"><Image src={image} alt={imageAlt} fill sizes="100vw" priority quality={85}/><div className="institution-shade"/><div className="container"><h1>{title}</h1></div></section>;}
export function BusinessHero({locale,title,description,image,imageAlt,items}:{locale:Locale;title:string;description:string;items:{title:string;href:string}[]}&HeroImage){return <section className="business-hero"><Image src={image} alt={imageAlt} fill sizes="100vw" priority quality={85}/><div className="business-shade"/><div className="container business-hero-grid"><div className="business-hero-heading"><SectionLabel>{text(locale,"OUR SERVICES","我們的服務","我们的服务")}</SectionLabel><h1>{title}</h1><p>{description}</p></div><nav className="business-hero-index" aria-label={text(locale,`${title} topics`,`${title}主題`,`${title}主题`,`مواضيع ${title}`)}><span className="eyebrow">{text(locale,"HOW WE HELP","我們如何協助","我们如何协助")}</span>{items.map(item=><Link key={item.href} href={item.href}>{item.title}<span aria-hidden="true">↗</span></Link>)}</nav></div></section>;}
export function AdvisoryHero({locale,category,title,description,image,imageAlt,parent="solutions",parentTitle}:{locale:Locale;category:string;title:ReactNode;description:string;parent?:string;parentTitle?:string}&HeroImage){return <section className="advisory-hero"><Image src={image} alt={imageAlt} fill sizes="100vw" priority quality={85}/><div className="advisory-shade"/><div className="advisory-container advisory-hero-grid"><div><nav className="advisory-breadcrumb" aria-label={text(locale,"Breadcrumb","頁面路徑","页面路径")}><Link href={pathFor(locale)}>{text(locale,"FIDERE","FIDERE","FIDERE")}</Link><span aria-hidden="true">/</span><Link href={pathFor(locale,parent)}>{parentTitle??text(locale,"Solutions","信託方案","信托方案")}</Link></nav><h1>{title}</h1><span className="advisory-category">{category}</span></div><div className="advisory-summary"><p>{description}</p><div className="advisory-actions"><TextLink className="button-solid" href={pathFor(locale,"contact")}>{text(locale,"Get in touch","聯絡我們","联系我们")}</TextLink><TextLink className="button-paper" href={pathFor(locale,parent)}>{text(locale,"View all","瀏覽全部","浏览全部")} {parentTitle??text(locale,"solutions","方案","方案")}</TextLink></div></div></div></section>;}
