import { ImageReveal, SectionLabel, TextLink } from "./editorial";
import { type SolutionDetailData } from "@/lib/solutions";
import { pathFor,text,type Locale } from "@/lib/site";
import "./solution-bodies.css";
type Props={locale:Locale;solution:SolutionDetailData};

function Considerations({locale,solution}:Props){return <section id="considerations" className="solution-considerations container"><SectionLabel>{text(locale,"SCOPE & CONSIDERATIONS","範圍與考量","范围与考量")}</SectionLabel><div><h2>{text(locale,"The terms matter.","條款，界定安排。","条款，界定安排。")}</h2><p>{text(locale,...solution.considerations)}</p><TextLink href={pathFor(locale,["transaction-support","equity-asset-custody"].includes(solution.slug)?"risk-fees":"compliance")}>{text(locale,"Read the applicable framework","了解適用框架","了解适用框架")}</TextLink></div></section>;}
function CapabilityRows({locale,solution}:Props){return <div className="capability-rows">{solution.capabilities.map((item,i)=><article key={item.title[0]}><span className="row-number">0{i+1}</span><h3>{text(locale,...item.title)}</h3><p>{text(locale,...item.body)}</p></article>)}</div>;}

export function PrivateTrustBody({locale,solution}:Props){
 const roles=[
  ["Settlor","委託人","委托人","The purpose and assets with which the arrangement begins.","提出安排目的，以及擬納入的資產。","提出安排目的，以及拟纳入的资产。"],
  ["Trustee","受託人","受托人","Holds and administers trust assets under the governing documents.","按管治文件持有及管理信託資產。","按治理文件持有及管理信托资产。"],
  ["Beneficiaries","受益人","受益人","The people entitled to benefit under the trust’s terms.","按信託條款享有利益的人士。","按信托条款享有利益的人士。"],
 ];
 return <><section id="overview" className="section container advisory-approach"><div><SectionLabel index="01">{text(locale,"PURPOSE BEFORE STRUCTURE","先明目的，再定架構","先明目的，再定架构")}</SectionLabel><h2>{text(locale,...solution.statement)}</h2><div className="advisory-tags">{roles.map(r=><span key={r[0]}>{text(locale,r[0],r[1],r[2])}</span>)}</div><p>{text(locale,...solution.overview)}</p></div><ImageReveal src="/images/hong-kong-architecture.jpg" alt={text(locale,"Architecture in Hong Kong","香港建築","香港建筑")} sizes="(max-width: 767px) 100vw, 50vw"/></section>
 <section className="trust-relationship dark-section"><div className="container"><SectionLabel>{text(locale,"A RELATIONSHIP, DEFINED","明確界定的關係","明确界定的关系")}</SectionLabel><h2>{text(locale,"Different roles.\nA shared framework.","角色有別，\n安排有序。","角色有别，\n安排有序。")}</h2><div className="trust-role-grid">{roles.map((r,i)=><article key={r[0]}><span className="row-number">0{i+1}</span><h3>{text(locale,r[0],r[1],r[2])}</h3><p>{text(locale,r[3],r[4],r[5])}</p></article>)}</div><p className="legal-note">{text(locale,"Illustrative roles only. The deed, applicable law and circumstances define the actual arrangement.","以上僅為角色示意，實際安排由信託契據、適用法律與個別情況界定。","以上仅为角色示意，实际安排由信托契据、适用法律与个别情况界定。")}</p></div></section>
 <section id="scope" className="section container"><div className="section-heading"><SectionLabel index="02">{text(locale,"HOW WE ACT","我們如何履責","我们如何履责")}</SectionLabel><h2>{text(locale,"From intention\nto administration.","從意向，\n到日常管理。","从意向，\n到日常管理。")}</h2></div><CapabilityRows locale={locale} solution={solution}/></section>
 <section className="container solution-context"><h2>{text(locale,"When to begin\nthe conversation.","何時開始\n這場對話。","何时开始\n这场对话。")}</h2><div><p>{text(locale,"You may be considering how assets are held, how family responsibilities will evolve, or how an existing structure is administered. These are starting points for discussion, rather than a conclusion that a trust is suitable.","您可能正在考慮資產的持有方式、家族責任的變化，或現有架構的管理。這些都是討論的起點，並不代表信託一定適合。","您可能正在考虑资产的持有方式、家族责任的变化，或现有架构的管理。这些都是讨论的起点，并不代表信托一定适合。")}</p><TextLink href={pathFor(locale,"solutions/succession-planning")}>{text(locale,"Consider succession planning","進一步了解傳承規劃","进一步了解传承规划")}</TextLink></div></section><Considerations locale={locale} solution={solution}/></>;
}

export function FamilyOfficeBody({locale,solution}:Props){return <><section id="overview" className="section container family-introduction"><div><SectionLabel index="01">{text(locale,"FAMILY WEALTH, IN CONTEXT","從家族整體出發","从家族整体出发")}</SectionLabel><h2>{text(locale,...solution.statement)}</h2></div><div><p className="body-large">{text(locale,...solution.overview)}</p><p>{text(locale,"A family’s administrative needs do not always follow the boundaries between accounts, entities and advisers. We consider the connections between them, with attention to what must remain clear as circumstances change.","家族的行政需要往往跨越賬戶、實體與顧問之間的界線。我們考慮各方聯繫，並關注情況變化時仍需保持清晰的事項。","家族的行政需要往往跨越账户、实体与顾问之间的界线。我们考虑各方联系，并关注情况变化时仍需保持清晰的事项。")}</p></div></section>
 <ImageReveal src="/images/coastal-horizon.jpg" alt={text(locale,"A quiet coastal horizon","平靜的海岸地平線","平静的海岸地平线")} className="family-wide-image" sizes="100vw"/>
 <section id="scope" className="section container family-scope"><aside><SectionLabel index="02">{text(locale,"COORDINATION & CONTINUITY","協調與延續","协调与延续")}</SectionLabel><h2>{text(locale,"A connected view\nof family affairs.","以相互連結的視野，\n考慮家族事務。","以相互连接的视野，\n考虑家族事务。")}</h2></aside><div>{solution.capabilities.map((c,i)=><article key={c.title[0]}><span className="row-number">0{i+1}</span><h3>{text(locale,...c.title)}</h3><p>{text(locale,...c.body)}</p></article>)}</div></section>
 <section className="container solution-context"><h2>{text(locale,"Across borders.\nAcross generations.","跨越地域。\n延續世代。","跨越地域。\n延续世代。")}</h2><div><p>{text(locale,"A family structure can involve more than one jurisdiction and more than one generation. Ownership information, account arrangements and decision protocols need to be considered together. The appropriate roles for legal, tax and other professional advisers depend on the family’s circumstances.","家族架構可能涉及多個司法管轄區與不同世代。所有權資料、賬戶安排及決策機制需要一併考慮。法律、稅務及其他專業顧問的適當角色，視乎家族情況而定。","家族架构可能涉及多个司法管辖区与不同世代。所有权资料、账户安排及决策机制需要一并考虑。法律、税务及其他专业顾问的适当角色，视乎家族情况而定。")}</p><TextLink href={pathFor(locale,"about/governance")}>{text(locale,"Governance in practice","了解治理安排","了解治理安排")}</TextLink></div></section><Considerations locale={locale} solution={solution}/></>;}

export function CorporateBody({locale,solution}:Props){return <><section id="overview" className="section container solution-context"><div><SectionLabel index="01">{text(locale,"THE STRUCTURE","架構背景","架构背景")}</SectionLabel><h2>{text(locale,...solution.statement)}</h2></div><p className="body-large">{text(locale,...solution.overview)}</p></section><section id="scope" className="section corporate-scope"><div className="container"><SectionLabel index="02">{text(locale,"ROLES & RESPONSIBILITIES","角色與責任","角色与责任")}</SectionLabel><CapabilityRows locale={locale} solution={solution}/><div className="corporate-due-diligence"><h3>{text(locale,"Begin with a clear ownership picture.","先釐清所有權。","先厘清所有权。")}</h3><TextLink href={pathFor(locale,"compliance/client-due-diligence")}>{text(locale,"Client due diligence","客戶盡職審查","客户尽职调查")}</TextLink></div></div></section><Considerations locale={locale} solution={solution}/></>;}

export function TransactionBody({locale,solution}:Props){return <><section id="overview" className="section container trust-introduction"><SectionLabel index="01">{text(locale,"THE ADMINISTRATIVE CONTEXT","管理背景","管理背景")}</SectionLabel><h2>{text(locale,...solution.statement)}</h2><p className="body-large">{text(locale,...solution.overview)}</p></section><section id="scope" className="section container transaction-scope"><div className="section-heading"><SectionLabel index="02">{text(locale,"INFORMATION · AUTHORITY · RECORDS","資料 · 授權 · 記錄","资料 · 授权 · 记录")}</SectionLabel><h2>{text(locale,"The details behind\nthe arrangement.","安排背後，\n每一項細節。","安排背后，\n每一项细节。")}</h2></div><ol className="transaction-sequence">{solution.capabilities.map((c,i)=><li key={c.title[0]}><span>0{i+1}</span><div><h3>{text(locale,...c.title)}</h3><p>{text(locale,...c.body)}</p></div></li>)}</ol></section><section className="container solution-context"><h2>{text(locale,"Clear instructions.\nDefined authority.","清晰指示。\n明確權限。","清晰指示。\n明确权限。")}</h2><div><p>{text(locale,"The person giving an instruction, the assets involved and the proposed movement need to be understood within the relevant mandate. A request may require further documentation or review before it can proceed. Timing also depends on the institutions and jurisdictions involved.","需要在相關授權範圍內，了解發出指示的人士、涉及資產與擬定流轉。要求可能需要補充文件或進一步覆核，方能繼續處理。時間亦視乎涉及的機構與司法管轄區。","需要在相关授权范围内，了解发出指示的人士、涉及资产与拟定流转。要求可能需要补充文件或进一步复核，方能继续处理。时间亦视乎涉及的机构与司法管辖区。")}</p><TextLink href={pathFor(locale,"compliance/source-of-funds")}>{text(locale,"Understanding the source of funds","了解資金來源","了解资金来源")}</TextLink></div></section><Considerations locale={locale} solution={solution}/></>;}

export function SuccessionBody({locale,solution}:Props){return <><section id="overview" className="section container succession-intro"><SectionLabel index="01">{text(locale,"A LONGER VIEW","更長遠的安排","更长远的安排")}</SectionLabel><h2>{text(locale,...solution.statement)}</h2><p className="body-large">{text(locale,...solution.overview)}</p></section><section id="scope" className="section container"><div className="section-heading"><SectionLabel index="02">{text(locale,"PLANNING & CONTINUITY","規劃與延續","规划与延续")}</SectionLabel><h2>{text(locale,"Consider the transition,\nnot only the transfer.","傳遞資產，\n也承接責任。","传递资产，\n也承接责任。")}</h2></div><CapabilityRows locale={locale} solution={solution}/></section><Considerations locale={locale} solution={solution}/></>;}

function GovernanceBody({locale,solution}:Props){return <><section id="overview" className="section container solution-context"><div><SectionLabel index="01">{text(locale,"PURPOSE & CONTEXT","目的與背景","目的与背景")}</SectionLabel><h2>{text(locale,...solution.statement)}</h2></div><p className="body-large">{text(locale,...solution.overview)}</p></section><section id="scope" className="section container governance-solution"><SectionLabel index="02">{text(locale,"THE WORK INVOLVED","相關工作","相关工作")}</SectionLabel><div className="detail-accordion">{solution.capabilities.map((c,i)=><details name="service-scope" key={c.title[0]} open={i===0}><summary><span className="row-number">0{i+1}</span><h3>{text(locale,...c.title)}</h3></summary><p>{text(locale,...c.body)}</p></details>)}</div></section><Considerations locale={locale} solution={solution}/></>;}
export function SolutionBody(props:Props){switch(props.solution.slug){case"private-trust":return <PrivateTrustBody {...props}/>;case"family-office":return <FamilyOfficeBody {...props}/>;case"corporate-trust":case"trustee-directors":case"company-formation":return <CorporateBody {...props}/>;case"transaction-support":case"equity-asset-custody":return <TransactionBody {...props}/>;case"succession-planning":return <SuccessionBody {...props}/>;default:return <GovernanceBody {...props}/>;}}
