import { notFound } from "next/navigation";
import { BreadcrumbStructuredData } from "@/components/breadcrumb-structured-data";
import { CTAEditorial, SectionLabel, TextLink } from "./editorial";
import { AdvisoryHero } from "./inner-heroes";
import { type Locale, pathFor, text } from "@/lib/site";
import { type WealthCopy, type WealthTopic, wealthTopics } from "@/lib/wealth-topics";
import "./wealth-insights.css";

const local = (locale: Locale, copy: WealthCopy) => text(locale, ...copy);

function TopicHero({ locale, topic }: { locale: Locale; topic: WealthTopic }) {
  return <AdvisoryHero
    locale={locale}
    parent="wealth-management"
    parentTitle={text(locale, "Wealth Management", "財富管理", "财富管理")}
    title={local(locale, topic.title)}
    category={local(locale, topic.title)}
    description={local(locale, topic.description)}
    image={topic.image}
    imageAlt={local(locale, topic.imageAlt)}
  />;
}

function Eligibility({ locale }: { locale: Locale }) {
  return <aside className="wi-eligibility"><SectionLabel>{text(locale, "AVAILABILITY & SCOPE", "服務資格與範圍", "服务资格与范围")}</SectionLabel><p>{text(locale, "Availability depends on client eligibility, jurisdiction, account arrangements and applicable requirements. Certain services are restricted to Professional Investors under Hong Kong’s Securities and Futures Ordinance (Cap. 571). These descriptions are not investment recommendations; returns and principal protection are not guaranteed.", "服務取決於客戶資格、司法管轄區、賬戶安排及適用要求。部分服務僅向香港《證券及期貨條例》（第571章）所界定的專業投資者提供。以下說明不構成投資建議；回報與本金保障均不獲保證。", "服务取决于客户资格、司法管辖区、账户安排及适用要求。部分服务仅向香港《证券及期货条例》（第571章）所界定的专业投资者提供。以下说明不构成投资建议；回报与本金保障均不获保证。")}</p></aside>;
}

function GlobalMarkets({ locale }: { locale: Locale }) {
  const layers: { title: WealthCopy; body: WealthCopy }[] = [
    { title: ["The market", "市場", "市场"], body: ["FIDERE’s published capabilities include access to US, Hong Kong and Chinese public equities, alongside other investment instruments. Specific access is subject to the account and client’s eligibility.", "FIDERE 已公佈能力包括美國、香港及中國上市股票，以及其他投資工具的渠道。具體渠道須視乎賬戶及客戶資格。", "FIDERE 已公布能力包括美国、香港及中国上市股票，以及其他投资工具的渠道。具体渠道须视乎账户及客户资格。"] },
    { title: ["The institution", "機構", "机构"], body: ["Brokerage, investment-account and custody arrangements sit with the relevant financial institutions. Their documentation, dealing conditions and operational requirements remain part of the arrangement.", "經紀、投資賬戶及託管安排涉及相關金融機構，其文件、交易條件與營運要求均是安排的一部分。", "经纪、投资账户及托管安排涉及相关金融机构，其文件、交易条件与运营要求均是安排的一部分。"] },
    { title: ["The trust", "信託", "信托"], body: ["Holding and administration must be considered within the trust’s terms. We coordinate the account arrangements and relevant records around the agreed scope of the structure.", "資產持有與管理須在信託條款內考慮。我們按照架構的約定範圍，協調賬戶安排及相關記錄。", "资产持有与管理须在信托条款内考虑。我们按照架构的约定范围，协调账户安排及相关记录。"] },
  ];
  return <><section className="section container wi-market-intro"><SectionLabel index="01">{text(locale, "A CONNECTED ARRANGEMENT", "相互連結的安排", "相互连接的安排")}</SectionLabel><div><h2>{text(locale, "The market is one part\nof the picture.", "市場，\n是整體的一部分。", "市场，\n是整体的一部分。")}</h2><p className="body-large">{text(locale, "An investment may be held in one jurisdiction, administered through an account in another, and form part of a wider trust. Access begins with understanding how those relationships fit together.", "一項投資可能位於某個司法管轄區，透過另一地區的賬戶管理，並屬於更廣泛信託安排的一部分。考慮渠道，始於理解這些關係如何連結。", "一项投资可能位于某个司法管辖区，通过另一地区的账户管理，并属于更广泛信托安排的一部分。考虑渠道，始于理解这些关系如何连接。")}</p></div></section><section className="container wi-market-layers" aria-label={text(locale, "Three connected layers", "三個相連層面", "三个相连层面")}>{layers.map((layer, index) => <article key={layer.title[0]}><span className="row-number">0{index + 1}</span><h2>{local(locale, layer.title)}</h2><p>{local(locale, layer.body)}</p></article>)}</section><section className="section dark-section"><div className="container wi-market-note"><h2>{text(locale, "Cross-border access.\nLocal requirements.", "跨境渠道，\n各地要求。", "跨境渠道，\n各地要求。")}</h2><div><p>{text(locale, "Market hours, currency, settlement procedures and client documentation can differ. An available market does not mean that every security or service is available to every client. The relevant account arrangements and restrictions should be established before instructions are given.", "市場時間、幣種、結算程序及客戶文件要求可能不同。某個市場可供接觸，不代表每名客戶均可使用所有證券或服務。發出指示前，應先確定相關賬戶安排與限制。", "市场时间、币种、结算程序及客户文件要求可能不同。某个市场可供接触，不代表每名客户均可使用所有证券或服务。发出指示前，应先确定相关账户安排与限制。")}</p><TextLink className="light-link" href={pathFor(locale, "insights/cross-border-administration")}>{text(locale, "Read the cross-border guide", "閱讀跨境安排指南", "阅读跨境安排指南")}</TextLink></div></div></section></>;
}

function Funds({ locale }: { locale: Locale }) {
  const questions: { title: WealthCopy; body: WealthCopy }[] = [
    { title: ["What does the fund hold?", "基金持有甚麼？", "基金持有什么？"], body: ["The mandate, underlying exposures and product documents help describe what an allocation represents. A familiar category name does not by itself explain the specific fund or its risks.", "投資範圍、相關資產及產品文件，有助說明配置的實際內容。熟悉的類別名稱，本身不足以解釋特定基金或其風險。", "投资范围、相关资产及产品文件，有助说明配置的实际内容。熟悉的类别名称，本身不足以解释特定基金或其风险。"] },
    { title: ["How can it be entered or exited?", "如何參與或退出？", "如何参与或退出？"], body: ["Dealing windows, settlement and redemption conditions should be read in the applicable product and account documents. Liquidity should be considered alongside the trust’s commitments, rather than assumed from a product label.", "應按適用產品及賬戶文件了解交易時段、結算及贖回條件。流動性須配合信託承擔的需要考慮，不能僅憑產品名稱推定。", "应按适用产品及账户文件了解交易时段、结算及赎回条件。流动性须配合信托承担的需要考虑，不能仅凭产品名称推定。"] },
    { title: ["Which charges and records apply?", "適用哪些費用與記錄？", "适用哪些费用与记录？"], body: ["Product costs and institution, custody or administration charges may arise at different points. Confirm the applicable documents, reporting arrangements and charges for the proposed holding before proceeding.", "產品成本及機構、託管或行政收費，可能在不同環節產生。進行前，應確認擬持有安排所適用的文件、報告方式及費用。", "产品成本及机构、托管或行政收费，可能在不同环节产生。进行前，应确认拟持有安排所适用的文件、报告方式及费用。"] },
  ];
  return <><section className="section container wi-fund-forms"><div className="wi-fund-heading"><SectionLabel index="01">{text(locale, "TWO FORMS OF ACCESS", "兩類基金渠道", "两类基金渠道")}</SectionLabel><h2>{text(locale, "Understand the vehicle\nbefore the allocation.", "配置之前，\n先理解工具。", "配置之前，\n先理解工具。")}</h2></div><div className="wi-fund-columns"><article><span className="row-number">01</span><h3>{text(locale, "Mutual funds", "共同基金", "共同基金")}</h3><p>{text(locale, "FIDERE’s published wealth capabilities include mutual funds. Any holding must be considered with the fund’s mandate, subscription and redemption terms, client eligibility and the relevant account arrangement.", "FIDERE 已公佈財富服務包括共同基金。任何持有安排均須考慮基金投資範圍、認購及贖回條款、客戶資格與相關賬戶安排。", "FIDERE 已公布财富服务包括共同基金。任何持有安排均须考虑基金投资范围、认购及赎回条款、客户资格与相关账户安排。")}</p></article><article><span className="row-number">02</span><h3>{text(locale, "Exchange-traded funds", "交易所買賣基金", "交易所买卖基金")}</h3><p>{text(locale, "ETF access is also described by FIDERE. The specific market, underlying exposure and dealing conditions matter alongside the instrument’s listing. Execution and custody depend on the relevant institution and account.", "FIDERE 亦披露 ETF 渠道。除上市地點外，具體市場、相關資產及交易條件同樣重要。執行與託管取決於相關機構及賬戶。", "FIDERE 亦披露 ETF 渠道。除上市地点外，具体市场、相关资产及交易条件同样重要。执行与托管取决于相关机构及账户。")}</p></article></div></section><section className="wi-fund-reading"><div className="container wi-fund-reading-grid"><div><SectionLabel index="02">{text(locale, "READING THE ARRANGEMENT", "理解具體安排", "理解具体安排")}</SectionLabel><h2>{text(locale, "Three questions\nworth keeping together.", "三個問題，\n一併考慮。", "三个问题，\n一并考虑。")}</h2></div><div className="wi-reading-list">{questions.map((item, index) => <details name="fund-reading" key={item.title[0]} open={index === 0}><summary><span className="row-number">0{index + 1}</span><h3>{local(locale, item.title)}</h3><span className="wi-plus" aria-hidden="true">+</span></summary><p>{local(locale, item.body)}</p></details>)}</div></div></section><section className="section container wi-reading-width"><SectionLabel index="03">{text(locale, "THE ADMINISTRATIVE ROLE", "管理角色", "管理角色")}</SectionLabel><h2>{text(locale, "Part of the wider trust record.", "納入整體信託記錄。", "纳入整体信托记录。")}</h2><p>{text(locale, "Our role is to coordinate holding and account administration within the agreed trust framework. A fund investment remains subject to its own documentation and risks. This page does not identify a recommended fund or offer a managed investment mandate.", "我們在約定信託框架內，協調持有與賬戶管理。基金投資仍須遵循其本身文件及風險安排。本頁不推薦特定基金，亦不提供投資管理委託。", "我们在约定信托框架内，协调持有与账户管理。基金投资仍须遵循其本身文件及风险安排。本页不推荐特定基金，亦不提供投资管理委托。")}</p><TextLink href={pathFor(locale, "risk-fees")}>{text(locale, "Risk and fee disclosures", "風險及費用披露", "风险及费用披露")}</TextLink></section></>;
}

function FixedIncome({ locale }: { locale: Locale }) {
  const factors: { title: WealthCopy; question: WealthCopy; body: WealthCopy }[] = [
    { title: ["Issuer", "發行人", "发行人"], question: ["Who is responsible for payment?", "誰負責付款？", "谁负责付款？"], body: ["Government and corporate bonds carry the obligations of their respective issuers. The security, terms and credit exposure should be considered for the particular instrument; the category alone is not a guarantee.", "政府及企業債券承載各自發行人的付款義務。須就個別工具考慮證券本身、條款及信貸風險，類別名稱本身並非保證。", "政府及企业债券承载各自发行人的付款义务。须就个别工具考虑证券本身、条款及信贷风险，类别名称本身并非保证。"] },
    { title: ["Term", "期限", "期限"], question: ["When are cash flows expected?", "預期何時收到現金流？", "预期何时收到现金流？"], body: ["The maturity and payment terms should be read together with the trust’s obligations. An expected payment schedule does not remove credit risk or assure the value of a position before maturity.", "到期日與付款條款，須配合信託的承擔一併理解。預期付款時間表，不消除信貸風險，也不保證到期前的持倉價值。", "到期日与付款条款，须配合信托的承担一并理解。预期付款时间表，不消除信贷风险，也不保证到期前的持仓价值。"] },
    { title: ["Liquidity", "流動性", "流动性"], question: ["What if the asset must be sold?", "如需出售資產，會如何？", "如需出售资产，会如何？"], body: ["Market conditions, available dealing channels and the instrument’s terms can affect an exit. Consider currency and settlement requirements as well as the ability to hold the position for the intended period.", "市場情況、可用交易渠道及工具條款，可能影響退出安排。除能否按預定期間持有外，亦須考慮幣種及結算要求。", "市场情况、可用交易渠道及工具条款，可能影响退出安排。除能否按预定期间持有外，亦须考虑币种及结算要求。"] },
  ];
  return <><section className="section container wi-fixed-statement"><SectionLabel index="01">{text(locale, "FIXED INCOME WITHIN THE STRUCTURE", "架構內的固定收益安排", "架构内的固定收益安排")}</SectionLabel><h2>{text(locale, "Issuer. Term. Liquidity.", "發行人。期限。流動性。", "发行人。期限。流动性。")}</h2><p>{text(locale, "FIDERE’s published wealth offering includes government and corporate bonds. Access is considered within the applicable account and custody framework. The instrument’s name is the start of the discussion, not the complete assessment.", "FIDERE 已公佈財富服務包括政府及企業債券，具體渠道須在適用賬戶與託管框架內考慮。工具名稱是討論的起點，並非完整評估。", "FIDERE 已公布财富服务包括政府及企业债券，具体渠道须在适用账户与托管框架内考虑。工具名称是讨论的起点，并非完整评估。")}</p></section><section className="container wi-fixed-factors" aria-label={text(locale, "Fixed-income considerations", "固定收益考量", "固定收益考量")}>{factors.map((factor, index) => <article key={factor.title[0]}><span className="row-number">0{index + 1}</span><h2>{local(locale, factor.title)}</h2><div><h3>{local(locale, factor.question)}</h3><p>{local(locale, factor.body)}</p></div></article>)}</section><section className="section container wi-fixed-end"><div><SectionLabel index="02">{text(locale, "HOLDING & ADMINISTRATION", "持有與管理", "持有与管理")}</SectionLabel><h2>{text(locale, "The record continues\nbeyond the purchase.", "買入之後，\n記錄仍需延續。", "买入之后，\n记录仍需延续。")}</h2></div><div><p>{text(locale, "Account and custody arrangements should be understood alongside the relevant product documents. Administration brings the holding, transaction and account records into the wider trust structure. Any investment decision requires consideration of the client’s circumstances and the specific instrument.", "賬戶及託管安排應與相關產品文件一併理解。管理工作將持有、交易及賬戶記錄納入整體信託架構。任何投資決定均須考慮客戶情況及具體工具。", "账户及托管安排应与相关产品文件一并理解。管理工作将持有、交易及账户记录纳入整体信托架构。任何投资决定均须考虑客户情况及具体工具。")}</p><TextLink href={pathFor(locale, "solutions/equity-asset-custody")}>{text(locale, "Asset custody arrangements", "資產託管安排", "资产托管安排")}</TextLink></div></section></>;
}

function CashManagement({ locale }: { locale: Locale }) {
  const sequence: { title: WealthCopy; body: WealthCopy }[] = [
    { title: ["Understand the commitments", "了解資金承擔", "了解资金承担"], body: ["Identify the payments and administrative obligations the structure is expected to meet. Timing and currency are part of that discussion, alongside the source and availability of funds.", "了解架構預期需要履行的付款及行政義務。除資金來源與可用性外，亦須討論時間與幣種。", "了解架构预期需要履行的付款及行政义务。除资金来源与可用性外，亦须讨论时间与币种。"] },
    { title: ["Consider the account arrangements", "考慮賬戶安排", "考虑账户安排"], body: ["Cash, fixed-deposit and money-market arrangements have different terms. Their availability and access conditions should be considered with the relevant institution, account and client eligibility.", "現金、定期存款及貨幣市場安排具有不同條款。應結合相關機構、賬戶及客戶資格，考慮其可用性與資金提取條件。", "现金、定期存款及货币市场安排具有不同条款。应结合相关机构、账户及客户资格，考虑其可用性与资金提取条件。"] },
    { title: ["Prepare for execution", "為執行作準備", "为执行作准备"], body: ["Supporting information, compliance checks and banking cut-off times may affect processing. A balance shown on an account does not, by itself, confirm that a particular instruction can settle immediately.", "證明資料、合規審查及銀行截止時間，可能影響處理。賬戶顯示的餘額，本身並不代表特定指示可以即時結算。", "证明资料、合规审查及银行截止时间，可能影响处理。账户显示的余额，本身并不代表特定指示可以即时结算。"] },
    { title: ["Maintain the administrative record", "維持管理記錄", "维持管理记录"], body: ["Keep transaction and account information connected to the trust’s wider records. Changes to expected activity or ownership may require updated information and further review.", "讓交易及賬戶資料與整體信託記錄保持連結。預期活動或所有權變動，可能需要更新資料及進一步覆核。", "让交易及账户资料与整体信托记录保持连接。预期活动或所有权变动，可能需要更新资料及进一步复核。"] },
  ];
  return <><section className="section container wi-cash-process"><div className="wi-cash-aside"><SectionLabel index="01">{text(locale, "FROM NEED TO ADMINISTRATION", "從需要到管理", "从需要到管理")}</SectionLabel><h2>{text(locale, "Cash has\na sequence.", "現金安排，\n環環相扣。", "现金安排，\n环环相扣。")}</h2><p>{text(locale, "Liquidity is considered in relation to the work the structure needs to do. Our role is to coordinate the account and administrative arrangements within the agreed scope.", "流動資金須配合架構需要履行的事項考慮。我們在約定範圍內，協調賬戶與行政安排。", "流动资金须配合架构需要履行的事项考虑。我们在约定范围内，协调账户与行政安排。")}</p></div><ol className="wi-cash-sequence">{sequence.map((step, index) => <li key={step.title[0]}><span className="row-number">0{index + 1}</span><div><h3>{local(locale, step.title)}</h3><p>{local(locale, step.body)}</p></div></li>)}</ol></section><section className="wi-cash-consideration dark-section"><div className="container"><SectionLabel index="02">{text(locale, "ACCESS IS A CONDITION", "提取條件", "提取条件")}</SectionLabel><h2>{text(locale, "A term, a dealing window,\na settlement process.", "期限、交易時段，\n以及結算程序。", "期限、交易时段，\n以及结算程序。")}</h2><p>{text(locale, "A deposit term and a fund’s dealing or redemption conditions are different arrangements. Each should be read in its own documents. Money-market instruments are investments and should not be treated as a promise of immediate cash availability or principal protection.", "存款期限與基金的交易或贖回條件，屬於不同安排，應分別閱讀各自文件。貨幣市場工具屬投資，不應視為即時資金可用性或本金保障的承諾。", "存款期限与基金的交易或赎回条件，属于不同安排，应分别阅读各自文件。货币市场工具属投资，不应视为即时资金可用性或本金保障的承诺。")}</p><TextLink className="light-link" href={pathFor(locale, "solutions/transaction-support")}>{text(locale, "Explore transaction support", "了解交易支持", "了解交易支持")}</TextLink></div></section></>;
}

function RelatedTopics({ locale, slug }: { locale: Locale; slug: string }) {
  return <section className="section container wi-related"><SectionLabel>{text(locale, "RELATED CAPABILITIES", "相關能力", "相关能力")}</SectionLabel><h2>{text(locale, "Consider the whole arrangement.", "從整體安排出發。", "从整体安排出发。")}</h2>{wealthTopics.filter((topic) => topic.slug !== slug).map((topic) => <div className="wi-related-row" key={topic.slug}><TextLink href={pathFor(locale, `wealth-management/${topic.slug}`)}>{local(locale, topic.title)}</TextLink><p>{local(locale, topic.description)}</p></div>)}</section>;
}

export function WealthTopicPage({ locale, slug }: { locale: Locale; slug: string }) {
  const topic = wealthTopics.find((entry) => entry.slug === slug);
  if (!topic) notFound();
  return <><BreadcrumbStructuredData locale={locale} items={[
    { name: text(locale, "Home", "首頁", "首页") },
    { name: text(locale, "Wealth Management", "財富管理", "财富管理"), slug: "wealth-management" },
    { name: local(locale, topic.title), slug: `wealth-management/${slug}` },
  ]} /><TopicHero locale={locale} topic={topic} /><div className="container"><Eligibility locale={locale} /></div>{slug === "global-markets" ? <GlobalMarkets locale={locale} /> : slug === "funds" ? <Funds locale={locale} /> : slug === "fixed-income" ? <FixedIncome locale={locale} /> : <CashManagement locale={locale} />}<RelatedTopics locale={locale} slug={slug} /><CTAEditorial locale={locale} /></>;
}
